### ISSUE TITLE
Compatibility with Raised

### ISSUE THREAD

**Issue by avsane** [ptayur/armor-weight#1]
It would be _really nice_ to see compatibility with the [Raised](https://modrinth.com/mod/raised). 
**From the mod page:**

> It fixes the code and texture that cuts off the hotbar selector texture on the bottom. As well, it allows you to move around the HUD elements on the screen!

**Comment by ptayur** [comment]
Compatibility with the Raised mod added in v1.1.1 (a008d1f).
